# netlify.toml file for performance optimization
[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[dev]
  framework = "vite"
  targetPort = 5173
  port = 8888
  autoLaunch = true

# Aggressive caching for images - they're hashed so can be cached forever
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    # Enable CORS for images to be loaded from CDNs
    Access-Control-Allow-Origin = "*"

# Specific image formats - webp
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/webp"

# Static JavaScript files - they're hashed so can be cached forever
[[headers]]
  for = "/assets/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# CSS files - they're hashed so can be cached forever
[[headers]]
  for = "/assets/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML and data should be revalidated more frequently
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"

# Enable HTTP/2 and Brotli compression
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Redirects - removing the problematic .netlify redirect 
[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Path = ["!/index.html"]}
